//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuLich_DH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int MaBinhLuan { get; set; }
        public string TenNguoiBinhLuan { get; set; }
        public string BinhLuan1 { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> MaDiaDiem { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
    
        public virtual DiaDiem DiaDiem { get; set; }
    }
}
