//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuLich_DH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachSan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachSan()
        {
            this.DatPhongs = new HashSet<DatPhong>();
        }
    
        public int MaKhachSan { get; set; }
        public string TenKhachSan { get; set; }
        public string SDT { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public string HinhAnhKS { get; set; }
        public Nullable<int> MaDiaDiem { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<double> DanhGia { get; set; }
        public Nullable<int> LuotDanhGia { get; set; }
        public string DiaChi { get; set; }
    
        public virtual DiaDiem DiaDiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatPhong> DatPhongs { get; set; }
    }
}
