//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuLich_DH.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class QuanTri
    {
        public int MaQuanTri { get; set; }
        [Required]
        [Remote("ktraTK", "TaiKhoan", HttpMethod = "POST", ErrorMessage = "Tai khoan da ton tai")]
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [System.Web.Mvc.Compare("MatKhau", ErrorMessage = "Mat khau khong trung khop")]
        public string NhapLaiMatKhau { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string QuenMatKhau { get; set; }
        public Nullable<bool> QuyenQuanTri { get; set; }
        public string AnhDaiDien { get; set; }
    }
}
